name: venera
description: "A comic app."
publish_to: 'none'

version: 1.3.1+131

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: 3.29.0

dependencies:
  flutter:
    sdk: flutter
  path_provider: any
  intl: any
  window_manager: ^0.4.3
  sqlite3: ^2.7.4
  sqlite3_flutter_libs: ^0.5.30
  flutter_qjs:
    git:
      url: https://github.com/wgh136/flutter_qjs
      ref: 5978d0c7784fbbefcacc573547f0ab01ba59b7b3
  crypto: ^3.0.6
  dio: ^5.8.0+1
  html: ^0.15.5
  pointycastle: ^4.0.0
  url_launcher: ^6.3.0
  path: ^1.9.0
  photo_view:
    git:
      url: https://github.com/wgh136/photo_view
      ref: d71faf3c75e059d013b0ce9ddaf5ecc1680e2eb6
  mime: ^2.0.0
  share_plus: ^10.1.4
  scrollable_positioned_list:
    git:
      url: https://github.com/venera-app/flutter.widgets
      ref: 09e756b1f1b04e6298318d99ec20a787fb360f59
      path: packages/scrollable_positioned_list
  flutter_reorderable_grid_view: ^5.4.0
  uuid: ^4.5.1
  desktop_webview_window:
    git:
      url: https://github.com/wgh136/flutter_desktop_webview
      path: packages/desktop_webview_window
  flutter_inappwebview:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview
      path: flutter_inappwebview
      ref: 0aaf7a0bfc01d61a4d1453cefb57fb6783b6e676
  app_links: ^6.4.0
  sliver_tools: ^0.2.12
  flutter_file_dialog: ^3.0.2
  file_selector: ^1.0.3
  zip_flutter: ^0.0.10
  lodepng_flutter:
    git:
      url: https://github.com/venera-app/lodepng_flutter
      ref: 9a784b193af5d55b2a35e58fa390bda3e4f35d00
  rhttp: 0.10.0
  webdav_client:
    git:
      url: https://github.com/wgh136/webdav_client
      ref: 285f87f15bccd2d5d5ff443761348c6ee47b98d1
  battery_plus: ^6.2.1
  local_auth: ^2.3.0
  flutter_saf:
    git: 
      url: https://github.com/pkuislm/flutter_saf.git
      ref: 7637b8b67d0a831f3cd7e702b8173e300880d32e
  dynamic_color: ^1.7.0
  shimmer_animation: ^2.1.0
  flutter_memory_info: ^0.0.1
  syntax_highlight: ^0.4.0
  flutter_7zip:
    git:
      url: https://github.com/wgh136/flutter_7zip
      ref: b33344797f1d2469339e0e1b75f5f954f1da224c
  flex_seed_scheme: ^3.5.0
  flutter_localizations:
    sdk: flutter
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_to_arch: ^1.0.1
  flutter_to_debian: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/translation.json
    - assets/init.js
    - assets/app_icon.png
    - assets/tags.json
    - assets/tags_tw.json

flutter_to_arch:
  name: Venera
  icon: debian/gui/venera.png
  categories: Utility
  keywords: Flutter;comic;images;
  url: https://github.com/venera-app/venera
  depends:
    - gtk3
    - webkit2gtk-4.1
