name: venera
description: "A comic app."
publish_to: 'none'

version: 1.0.1+101

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: 3.24.4

dependencies:
  flutter:
    sdk: flutter
  path_provider: any
  flutter_localizations:
    sdk: flutter
  intl: any
  window_manager: ^0.4.2
  sqlite3: any
  sqlite3_flutter_libs: any
  flutter_qjs:
    git:
      url: https://github.com/wgh136/flutter_qjs
      ref: ade0b9d
  crypto: any
  dio: any
  html: any
  pointycastle: any
  url_launcher: ^6.3.0
  path: ^1.9.0
  photo_view:
    git:
      url: https://github.com/wgh136/photo_view
      ref: 94724a0b
  mime: ^1.0.5
  share_plus: ^10.0.2
  scrollable_positioned_list:
    git:
      url: https://github.com/venera-app/flutter.widgets
      ref: 09e756b1f1b04e6298318d99ec20a787fb360f59
      path: packages/scrollable_positioned_list
  flutter_reorderable_grid_view: 5.0.1
  yaml: any
  uuid: ^4.5.1
  desktop_webview_window:
    git:
      url: https://github.com/wgh136/flutter_desktop_webview
      path: packages/desktop_webview_window
  flutter_inappwebview: ^6.1.5
  app_links: ^6.3.2
  sliver_tools: ^0.2.12
  flutter_file_dialog: ^3.0.2
  file_selector: ^1.0.3
  zip_flutter:
    git:
      url: https://github.com/wgh136/zip_flutter
  lodepng_flutter:
    git:
      url: https://github.com/venera-app/lodepng_flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_to_arch:
    git: https://github.com/wgh136/flutter_to_arch
  flutter_to_debian:

flutter:
  uses-material-design: true
  assets:
    - assets/translation.json
    - assets/init.js
    - assets/app_icon.png
    - assets/tags.json
    - assets/tags_tw.json

flutter_to_arch:
  name: Venera
  icon: debian/gui/venera.png
  categories: Utility
  keywords: Flutter;comic;images;
  url: https://github.com/venera-app/venera
  depends:
    - gtk3
    - webkit2gtk-4.1