name: Build IOS
run-name: Build IOS
on:
  workflow_dispatch: {}
jobs:
  Build_MacOS:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
          architecture: x64
      - run: sudo xcode-select --switch /Applications/Xcode_16.0.app
      - run: flutter pub get
        # Step 1: Decode and install the certificate
      - name: Decode and install certificate
        env:
          CERTIFICATE: ${{ secrets.CERTIFICATE }}
          CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
        run: |
          echo "$CERTIFICATE" | base64 --decode > signing_certificate.p12
          security import signing_certificate.p12 -k ~/Library/Keychains/login.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign

      # Step 2: Build the Flutter macOS app
      - name: Build Flutter macOS App
        run: flutter build macos --release

      # Step 3: Create the DMG file
      - name: Create DMG
        run: |
          mkdir -p dist
          mkdir -p dist/dmg_contents
          cp -R build/macos/Build/Products/Release/venera.app dist/dmg_contents/
          ln -s /Applications dist/dmg_contents/Applications
          hdiutil create -volname "venera" -srcfolder dist/dmg_contents -ov -format UDZO "dist/venera.dmg"

      # Step 4: Attach and upload artifacts (optional)
      - name: Upload DMG
        uses: actions/upload-artifact@v4
        with:
          name: venera.dmg
          path: dist/venera.dmg
  Build_IOS:
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
          architecture: x64
      - run: sudo xcode-select --switch /Applications/Xcode_16.0.app
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - run: |
          mkdir -p /Users/runner/work/venera/venera/build/ios/iphoneos/Payload
          mv /Users/runner/work/venera/venera/build/ios/iphoneos/Runner.app /Users/runner/work/venera/venera/build/ios/iphoneos/Payload
          cd /Users/runner/work/venera/venera/build/ios/iphoneos/
          zip -r venera-ios.ipa Payload
      - uses: actions/upload-artifact@v4
        with:
          name: app-ios.ipa
          path: /Users/runner/work/venera/venera/build/ios/iphoneos/venera-ios.ipa
